// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLLDnr5ohb4jnU3SOn0uMBDWfOUYZ_vs',
    appId: '1:189661517639:web:55431d5b0775ecc0f01e62',
    messagingSenderId: '189661517639',
    projectId: 'influence-6c544',
    authDomain: 'influence-6c544.firebaseapp.com',
    storageBucket: 'influence-6c544.firebasestorage.app',
    measurementId: 'G-YB4BE4TH2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjtTcUTgEUl-0ynRmJj5IlZAPXukSo6w',
    appId: '1:189661517639:android:bbea30202adf9204f01e62',
    messagingSenderId: '189661517639',
    projectId: 'influence-6c544',
    storageBucket: 'influence-6c544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1V-INpNoH8LHRdqBqf7LODhT9ujZA_g',
    appId: '1:189661517639:ios:2b3ab389160e285bf01e62',
    messagingSenderId: '189661517639',
    projectId: 'influence-6c544',
    storageBucket: 'influence-6c544.firebasestorage.app',
    iosBundleId: 'com.influence.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz1V-INpNoH8LHRdqBqf7LODhT9ujZA_g',
    appId: '1:189661517639:ios:f32bc243351d9c56f01e62',
    messagingSenderId: '189661517639',
    projectId: 'influence-6c544',
    storageBucket: 'influence-6c544.firebasestorage.app',
    iosBundleId: 'com.example.brandInfluencerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmLLDnr5ohb4jnU3SOn0uMBDWfOUYZ_vs',
    appId: '1:189661517639:web:eb7e4a263a373204f01e62',
    messagingSenderId: '189661517639',
    projectId: 'influence-6c544',
    authDomain: 'influence-6c544.firebaseapp.com',
    storageBucket: 'influence-6c544.firebasestorage.app',
    measurementId: 'G-QC3TGGMJRK',
  );
}
